# Generated by Django 4.0.4 on 2023-04-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0003_profile_remove_post_likes_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
