# Generated by Django 4.0.4 on 2023-04-21 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_media", "0007_remove_profile_followed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(blank=True, related_name="profiles", to=settings.AUTH_USER_MODEL),
        ),
    ]
