# Generated by Django 4.0.4 on 2023-04-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0008_profile_following"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="following",
            new_name="followers",
        ),
    ]
