# Generated by Django 4.0.4 on 2023-04-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0009_rename_following_profile_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follow",
            field=models.BooleanField(default=False),
        ),
    ]
